language: c
sudo: false

matrix:
    include:
        # Unfortunately, building configuration-tools with cabal < 1.22 is tricky,
        # so we disable this for now. Generally, it should be possible to build
        # with GHC 7.8
        # - env: CABALVER=1.18 GHCVER=7.8.4
        #   addons: {apt: {packages: [cabal-install-1.18,ghc-7.8.4], sources: [hvr-ghc]}}

        - env: CABALVER=1.22 GHCVER=7.10.3 DEEPSEQ="--constraint=deepseq>=1.4"
          addons: {apt: {packages: [cabal-install-1.22,ghc-7.10.3],sources: [hvr-ghc]}}
        - env: CABALVER=1.22 GHCVER=7.10.3 AESON="--constraint=aeson<0.11"
          addons: {apt: {packages: [cabal-install-1.22,ghc-7.10.3],sources: [hvr-ghc]}}
        - env: CABALVER=1.22 GHCVER=7.10.3 AESON="--constraint=aeson==0.11.0.0"
          addons: {apt: {packages: [cabal-install-1.22,ghc-7.10.3],sources: [hvr-ghc]}}
        - env: CABALVER=1.22 GHCVER=7.10.3
          addons: {apt: {packages: [cabal-install-1.22,ghc-7.10.3],sources: [hvr-ghc]}}

        - env: CABALVER=1.24 GHCVER=8.0.1
          addons: {apt: {packages: [cabal-install-1.24,ghc-8.0.1],sources: [hvr-ghc]}}

before_install:
    - export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:$PATH

install:
    - cabal --version
    - echo "$(ghc --version) [$(ghc --print-project-git-commit-id 2> /dev/null || echo '?')]"
    - travis_retry cabal update
    - cabal install --only-dependencies --enable-tests $DEEPSEQ $AESON

script:
    - cabal configure --enable-tests $DEEPSEQ $AESON
    - cabal build
    - travis_wait cabal test --show-details=streaming -v
    - cabal check
    - cabal sdist
    - SRC_TGZ=$(cabal info . | awk '{print $2;exit}').tar.gz &&
      (cd dist && cabal install --force-reinstalls $DEEPSEQ $AESON "$SRC_TGZ")

